CREATE TABLE IF NOT EXISTS integraciones_config (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  proveedor VARCHAR(30) NOT NULL,
  estado VARCHAR(20) NOT NULL DEFAULT 'desconectado',
  access_token_enc TEXT NULL,
  refresh_token_enc TEXT NULL,
  token_type VARCHAR(30) NULL,
  scope TEXT NULL,
  external_user_id VARCHAR(120) NULL,
  external_user_name VARCHAR(255) NULL,
  token_expires_at DATETIME NULL,
  refresh_token_expires_at DATETIME NULL,
  webhook_secret_enc TEXT NULL,
  metadata_json LONGTEXT NULL,
  ultimo_sync_en DATETIME NULL,
  ultimo_error TEXT NULL,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_integraciones_config_proveedor (proveedor),
  KEY ix_integraciones_config_estado (estado),
  KEY ix_integraciones_config_activo (activo),
  KEY ix_integraciones_config_expira (token_expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mp_payment_links (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  venta_id BIGINT UNSIGNED NOT NULL,
  integracion_config_id BIGINT UNSIGNED NULL,
  mp_preference_id VARCHAR(120) NOT NULL,
  mp_payment_id VARCHAR(120) NULL,
  external_reference VARCHAR(120) NULL,
  init_point TEXT NOT NULL,
  sandbox_init_point TEXT NULL,
  estado VARCHAR(30) NOT NULL DEFAULT 'pendiente',
  payment_status_detail VARCHAR(120) NULL,
  local_pago_id BIGINT UNSIGNED NULL,
  expires_at DATETIME NULL,
  last_seen_at DATETIME NULL,
  payload_json LONGTEXT NULL,
  creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_mp_payment_links_venta (venta_id),
  UNIQUE KEY uq_mp_payment_links_preference (mp_preference_id),
  UNIQUE KEY uq_mp_payment_links_payment (mp_payment_id),
  UNIQUE KEY uq_mp_payment_links_pago_local (local_pago_id),
  KEY ix_mp_payment_links_estado (estado),
  KEY ix_mp_payment_links_last_seen (last_seen_at),
  CONSTRAINT fk_mp_payment_links_venta FOREIGN KEY (venta_id) REFERENCES ventas(id) ON DELETE CASCADE,
  CONSTRAINT fk_mp_payment_links_config FOREIGN KEY (integracion_config_id) REFERENCES integraciones_config(id) ON DELETE SET NULL,
  CONSTRAINT fk_mp_payment_links_pago_local FOREIGN KEY (local_pago_id) REFERENCES pagos(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ml_product_sync (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  producto_id BIGINT UNSIGNED NOT NULL,
  integracion_config_id BIGINT UNSIGNED NULL,
  ml_item_id VARCHAR(120) NOT NULL,
  ml_permalink TEXT NULL,
  estado_publicacion VARCHAR(30) NOT NULL DEFAULT 'active',
  precio_publicado DECIMAL(18,2) NULL,
  stock_publicado INT NULL,
  ultimo_sync_en DATETIME NULL,
  ultimo_error TEXT NULL,
  payload_json LONGTEXT NULL,
  creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_ml_product_sync_producto (producto_id),
  UNIQUE KEY uq_ml_product_sync_item (ml_item_id),
  KEY ix_ml_product_sync_estado (estado_publicacion),
  KEY ix_ml_product_sync_sync (ultimo_sync_en),
  CONSTRAINT fk_ml_product_sync_producto FOREIGN KEY (producto_id) REFERENCES productos(id) ON DELETE CASCADE,
  CONSTRAINT fk_ml_product_sync_config FOREIGN KEY (integracion_config_id) REFERENCES integraciones_config(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ml_orders_import (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ml_order_id VARCHAR(120) NOT NULL,
  integracion_config_id BIGINT UNSIGNED NULL,
  venta_id BIGINT UNSIGNED NULL,
  ml_buyer_id VARCHAR(120) NULL,
  ml_shipping_id VARCHAR(120) NULL,
  ml_pack_id VARCHAR(120) NULL,
  estado_orden VARCHAR(40) NULL,
  estado_importacion VARCHAR(20) NOT NULL DEFAULT 'pendiente',
  total_order DECIMAL(18,2) NULL,
  fecha_orden DATETIME NULL,
  importado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ultimo_error TEXT NULL,
  payload_json LONGTEXT NULL,
  creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_ml_orders_import_order (ml_order_id),
  UNIQUE KEY uq_ml_orders_import_venta (venta_id),
  KEY ix_ml_orders_import_buyer (ml_buyer_id),
  KEY ix_ml_orders_import_pack (ml_pack_id),
  KEY ix_ml_orders_import_estado_orden (estado_orden),
  KEY ix_ml_orders_import_estado_importacion (estado_importacion),
  KEY ix_ml_orders_import_fecha (fecha_orden),
  CONSTRAINT fk_ml_orders_import_config FOREIGN KEY (integracion_config_id) REFERENCES integraciones_config(id) ON DELETE SET NULL,
  CONSTRAINT fk_ml_orders_import_venta FOREIGN KEY (venta_id) REFERENCES ventas(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
