CREATE TABLE IF NOT EXISTS api_keys (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) NOT NULL,
  key_hash VARCHAR(128) NOT NULL,
  permisos_json JSON NULL,
  ultimo_uso DATETIME NULL,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_api_keys_hash (key_hash),
  KEY ix_api_keys_activo (activo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS automation_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  event_name VARCHAR(120) NOT NULL,
  aggregate_type VARCHAR(80) NOT NULL,
  aggregate_id BIGINT UNSIGNED NULL,
  idempotency_key VARCHAR(190) NOT NULL,
  payload_json JSON NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  max_attempts INT UNSIGNED NOT NULL DEFAULT 8,
  locked_at DATETIME NULL,
  next_attempt_at DATETIME NULL,
  last_error TEXT NULL,
  delivered_at DATETIME NULL,
  response_status INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_automation_events_idempotency (idempotency_key),
  KEY ix_automation_events_queue (status, next_attempt_at, locked_at),
  KEY ix_automation_events_name (event_name),
  KEY ix_automation_events_aggregate (aggregate_type, aggregate_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS whatsapp_mensajes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  cliente_id BIGINT UNSIGNED NULL,
  telefono_e164 VARCHAR(20) NOT NULL,
  direccion ENUM('enviado', 'recibido') NOT NULL,
  tipo ENUM('texto', 'plantilla', 'documento', 'imagen') NOT NULL DEFAULT 'texto',
  contenido TEXT NULL,
  plantilla_codigo VARCHAR(100) NULL,
  plantilla_variables JSON NULL,
  media_url TEXT NULL,
  provider VARCHAR(30) NOT NULL DEFAULT 'twilio',
  provider_message_sid VARCHAR(160) NULL,
  provider_status VARCHAR(60) NULL,
  provider_error_code VARCHAR(60) NULL,
  campaign_id BIGINT UNSIGNED NULL,
  automatizado TINYINT(1) NOT NULL DEFAULT 0,
  automatizacion_nombre VARCHAR(120) NULL,
  payload_json JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_whatsapp_mensajes_provider_sid (provider, provider_message_sid),
  KEY ix_whatsapp_mensajes_cliente (cliente_id),
  KEY ix_whatsapp_mensajes_telefono (telefono_e164),
  KEY ix_whatsapp_mensajes_campaign (campaign_id),
  KEY ix_whatsapp_mensajes_created (created_at),
  CONSTRAINT fk_whatsapp_mensajes_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL,
  CONSTRAINT fk_whatsapp_mensajes_campaign FOREIGN KEY (campaign_id) REFERENCES whatsapp_campaigns(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
