import type { FinanceTabGuide } from './types';

export const FINANCE_TAB_GUIDES: FinanceTabGuide[] = [
  {
    key: 'bruta',
    label: 'Ganancia bruta',
    queMide: 'Cuanto queda de ventas despues de restar solo costo de productos.',
    comoLeer: 'Si cae con ventas altas, hay problema de costos, descuentos o mezcla de productos.',
    accion: 'Revisar top productos de bajo margen y ajustar precios u ofertas.',
  },
  {
    key: 'neta',
    label: 'Ganancia neta',
    queMide: 'Resultado final luego de costos, gastos e inversiones del periodo.',
    comoLeer: 'Un neto positivo sostenido confirma salud operativa; negativo exige correccion inmediata.',
    accion: 'Bajar gastos no criticos y priorizar cobranzas de deuda vencida.',
  },
  {
    key: 'producto',
    label: 'Ganancia por producto',
    queMide: 'Rentabilidad por SKU: ingresos, costo, ganancia y margen porcentual.',
    comoLeer: 'Detecta productos que venden mucho pero aportan poco margen.',
    accion: 'Subir precio, negociar costo o limitar promociones en SKU de bajo aporte.',
  },
  {
    key: 'costos',
    label: 'Costos de productos',
    queMide: 'Costo total de compras y cantidades por articulo en el rango elegido.',
    comoLeer: 'Picos de costo sin crecimiento de ventas anticipan compresion de margen.',
    accion: 'Revisar proveedor, frecuencia de compra y costo en dolares por categoria.',
  },
  {
    key: 'categorias',
    label: 'Por categoria',
    queMide: 'Rentabilidad agrupada por categoria comercial.',
    comoLeer: 'Sirve para decidir donde acelerar ventas y donde proteger margen.',
    accion: 'Invertir en categorias rentables y replantear las de margen bajo.',
  },
  {
    key: 'clientes',
    label: 'Por cliente',
    queMide: 'Aporte economico por cliente, incluyendo deuda y margen.',
    comoLeer: 'Un cliente con alta venta y baja rentabilidad puede consumir caja.',
    accion: 'Renegociar condiciones, cupo y politica de descuentos por cliente.',
  },
  {
    key: 'cobranzas',
    label: 'Cobranzas',
    queMide: 'Riesgo de mora, promesas de pago y recordatorios enviados.',
    comoLeer: 'Bucket critico/alto y deuda >90 dias requieren gestion prioritaria.',
    accion: 'Ejecutar recordatorios automaticos y seguimiento de promesas incumplidas.',
  },
  {
    key: 'alertas',
    label: 'Alertas',
    queMide: 'Alertas accionables del centro de mando (caja, deuda y stock).',
    comoLeer: 'Mas alertas criticas abiertas implica mayor riesgo operativo.',
    accion: 'Resolver alertas por severidad y cerrar solo cuando la causa se normalice.',
  },
  {
    key: 'margenes',
    label: 'Margenes',
    queMide: 'Margen en tiempo real por producto, vendedor o deposito.',
    comoLeer: 'Comparar entidades ayuda a detectar desvio comercial o de costo.',
    accion: 'Reentrenar equipo, ajustar surtido o mover stock segun performance.',
  },
  {
    key: 'repricing',
    label: 'Repricing',
    queMide: 'Impacto esperado y aplicado de reglas de actualizacion de precios.',
    comoLeer: 'Si el delta sugerido sube mucho, validar elasticidad antes de aplicar masivo.',
    accion: 'Usar preview, aplicar por lotes y monitorear margen y conversion.',
  },
  {
    key: 'fiscal',
    label: 'Fiscal AR',
    queMide: 'Retenciones y percepciones simuladas con reglas parametrizadas.',
    comoLeer: 'Permite estimar carga fiscal antes de emitir comprobantes.',
    accion: 'Corregir reglas de jurisdiccion y alicuotas segun normativa vigente.',
  },
  {
    key: 'precios',
    label: 'Listas de precios',
    queMide: 'Estrategia de listas, reglas y simulacion por producto.',
    comoLeer: 'Variaciones altas deben explicarse por costo, dolar o politica comercial.',
    accion: 'Aprobar solo cambios que preserven margen minimo por categoria.',
  },
  {
    key: 'integraciones',
    label: 'Integraciones',
    queMide: 'Estado de canales y jobs de sincronizacion.',
    comoLeer: 'Jobs fallidos recurrentes indican riesgo de inconsistencia comercial.',
    accion: 'Resolver credenciales, reintentos y monitoreo por canal.',
  },
  {
    key: 'beta',
    label: 'Programa beta',
    queMide: 'Adopcion e impacto real de clientes beta con feedback medible.',
    comoLeer: 'NPS bajo o impacto bajo pide ajuste de producto antes de escalar.',
    accion: 'Priorizar fixes del feedback con mayor impacto en caja y margen.',
  },
  {
    key: 'release',
    label: 'Release train',
    queMide: 'Ciclos mensuales, objetivos y changelog de negocio.',
    comoLeer: 'Ayuda a verificar si cada release movio KPIs clave.',
    accion: 'Cerrar ciclo solo con evidencia de impacto y sin deuda critica.',
  },
  {
    key: 'ofertas',
    label: 'Ofertas',
    queMide: 'Performance del motor de ofertas sobre ventas y margen.',
    comoLeer: 'Descuento alto sin aumento de volumen erosiona rentabilidad.',
    accion: 'Mantener ofertas con uplift real y pausar las que destruyen margen.',
  },
  {
    key: 'cashflow',
    label: 'Flujo de caja',
    queMide: 'Entradas, salidas y saldo acumulado diario/mensual.',
    comoLeer: 'Dias bajo umbral minimo son senal temprana de tension de caja.',
    accion: 'Acelerar cobranzas y diferir egresos no criticos.',
  },
  {
    key: 'presupuestos',
    label: 'Presupuestos',
    queMide: 'Comparativo presupuesto vs real por categoria y tipo.',
    comoLeer: 'Desvios recurrentes muestran planificacion imprecisa o ejecucion deficiente.',
    accion: 'Ajustar presupuesto mensual y asignar responsables por desvio.',
  },
];

export const PIE_COLORS = ['#22c55e', '#0ea5e9', '#a855f7', '#f97316', '#eab308', '#14b8a6', '#ef4444', '#64748b'];
